### ISSUE TITLE
Allow mounting specific AZ mount target

### ISSUE THREAD

**Issue by jfautley** [aws/efs-utils#10]
In a similar vein to #9, we cannot rely on the Amazon DNS servers resolving the correct mount target IP for our AZ as we're using Directory Service for our VPC DNS.

The `dns_name_format` option in the configuration file seems like an ideal place to add a `{az}` replacement, to allow mounting `{az}.{fs_id}.efs.{region}.amazonaws.com`.

I'm happy to raise a PR for this, but I'm not sure how long the per-AZ mount points are going to be around for, based on the [docs](https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html) (which states they're only there for 'backwards compatibility').

**Comment by joetrav** [comment]
Thank you for the feature request.  We will share it with the Directory Service and DNS teams as well.

**Comment by claco** [comment]
Nearly the same problem we have if your using caching servers inside of the VPC for various reasons.

https://github.com/aws/efs-utils/issues/21#issuecomment-479009440

**Comment by exeral** [comment]
Hello,

Thanks for the fix.
however I spent around 1 hour to understand the issue and find this issue which reference the fix commit where I found the readme update with the "az" parameter
This should be documented somewhere in the official AWS documentation.
