### ISSUE TITLE
Unable to configure STunnel Global Opts

### ISSUE THREAD

**Issue by Enquier** [aws/efs-utils#100]
Working on integrating efs with our environment and it looks like you can't configure all of the stunnel options in `mount_efs/__init__.py` "STUNNEL_GLOBAL_CONFIG". 

```
STUNNEL_GLOBAL_CONFIG = {    
    'fips': 'no',   
    'foreground': 'yes',   
     'socket': [       
             'l:SO_REUSEADDR=yes',      
             'a:SO_BINDTODEVICE=lo',    
     ],
}
```

Is that correct? Can that be fixed easily? Currently I am using a regex solution to find replace the values in /usr/sbin/mount.efs but i'd prefer "proper" configuration.

**Comment by Cappuccinuo** [comment]
Hey @Enquier ,

Yes the global config is fixed in the src file. The values can be moved to config file.

Wanna to know which options are you specifically interested in modify in your case?
