### ISSUE TITLE
make rpm is failing 

### ISSUE THREAD

**Issue by kunalgautam87** [aws/efs-utils#102]
rm -rf build/rpmbuild
rm -rf amazon-efs-utils
rm -f amazon-efs-utils.tar.gz
mkdir -p amazon-efs-utils
mkdir -p amazon-efs-utils/dist
cp -p dist/amazon-efs-mount-watchdog.conf amazon-efs-utils/dist
cp -p dist/amazon-efs-mount-watchdog.service amazon-efs-utils/dist
cp -p dist/efs-utils.conf amazon-efs-utils/dist
cp -p dist/efs-utils.crt amazon-efs-utils/dist
mkdir -p amazon-efs-utils/src
cp -rp src/mount_efs amazon-efs-utils/src
cp -rp src/watchdog amazon-efs-utils/src
mkdir -p amazon-efs-utils/man
cp -rp man/mount.efs.8 amazon-efs-utils/man
tar -czf amazon-efs-utils.tar.gz amazon-efs-utils/*
mkdir -p build/rpmbuild/{SPECS,COORD_SOURCES,DATA_SOURCES,BUILD,RPMS,SOURCES,SRPMS}
cp amazon-efs-utils.spec build/rpmbuild/SPECS
cp amazon-efs-utils.tar.gz build/rpmbuild/SOURCES
rpmbuild -ba --define "_topdir `pwd`/build/rpmbuild" build/rpmbuild/SPECS/amazon-efs-utils.spec
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.IwAscb
+ umask 022
+ cd /home/ec2-user/efs-utils/build/rpmbuild/BUILD
+ cd /home/ec2-user/efs-utils/build/rpmbuild/BUILD
+ rm -rf amazon-efs-utils
+ /usr/bin/tar -xvvf -
+ /usr/bin/gzip -dc /home/ec2-user/efs-utils/build/rpmbuild/SOURCES/amazon-efs-utils.tar.gz
drwx------ root/root         0 2021-06-18 10:22 amazon-efs-utils/dist/
drwxr-xr-x                  Creating directory: amazon-efs-utils
-rw------- ec2-user/ec2-user 590 2021-06-18 09:24 amazon-efs-utils/dist/amazon-efs-mount-watchdog.conf
-rw------- ec2-user/ec2-user 502 2021-06-18 09:24 amazon-efs-utils/dist/amazon-efs-mount-watchdog.service
-rw------- ec2-user/ec2-user 2506 2021-06-18 09:24 amazon-efs-utils/dist/efs-utils.conf
-rw------- ec2-user/ec2-user 4879 2021-06-18 09:24 amazon-efs-utils/dist/efs-utils.crt
drwx------ root/root            0 2021-06-18 10:22 amazon-efs-utils/man/
-rw------- ec2-user/ec2-user 9499 2021-06-18 09:24 amazon-efs-utils/man/mount.efs.8
drwx------ root/root            0 2021-06-18 10:22 amazon-efs-utils/src/
drwx------ ec2-user/ec2-user    0 2021-06-18 09:29 amazon-efs-utils/src/mount_efs/
-rw------- ec2-user/ec2-user 113253 2021-06-18 09:24 amazon-efs-utils/src/mount_efs/__init__.py
drwx------ ec2-user/ec2-user      0 2021-06-18 09:29 amazon-efs-utils/src/watchdog/
-rw------- ec2-user/ec2-user  54733 2021-06-18 09:24 amazon-efs-utils/src/watchdog/__init__.py
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd amazon-efs-utils
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ $'\r'
/var/tmp/rpm-tmp.IwAscb: line 37: $'\r': command not found
error: Bad exit status from /var/tmp/rpm-tmp.IwAscb (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.IwAscb (%prep)
make: *** [rpm-only] Error 1

[root@ip-x-x-x-x efs-utils]#cat /var/tmp/rpm-tmp.IwAscb
#!/bin/sh

  RPM_SOURCE_DIR="/home/ec2-user/efs-utils/build/rpmbuild/SOURCES"
  RPM_BUILD_DIR="/home/ec2-user/efs-utils/build/rpmbuild/BUILD"
  RPM_OPT_FLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic"
  RPM_LD_FLAGS="-Wl,-z,relro "
  RPM_ARCH="x86_64"
  RPM_OS="linux"
  export RPM_SOURCE_DIR RPM_BUILD_DIR RPM_OPT_FLAGS RPM_LD_FLAGS RPM_ARCH RPM_OS
  RPM_DOC_DIR="/usr/share/doc"
  export RPM_DOC_DIR
  RPM_PACKAGE_NAME="amazon-efs-utils"
  RPM_PACKAGE_VERSION="1.31.2"
  RPM_PACKAGE_RELEASE="1.el7"
  export RPM_PACKAGE_NAME RPM_PACKAGE_VERSION RPM_PACKAGE_RELEASE
  LANG=C
  export LANG
  unset CDPATH DISPLAY ||:
  RPM_BUILD_ROOT="/home/ec2-user/efs-utils/build/rpmbuild/BUILDROOT/amazon-efs-utils-1.31.2-1.el7.x86_64"
  export RPM_BUILD_ROOT

  PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/lib64/pkgconfig:/usr/share/pkgconfig"
  export PKG_CONFIG_PATH

  set -x
  umask 022
  cd "/home/ec2-user/efs-utils/build/rpmbuild/BUILD"
cd '/home/ec2-user/efs-utils/build/rpmbuild/BUILD'
rm -rf 'amazon-efs-utils'
/usr/bin/gzip -dc '/home/ec2-user/efs-utils/build/rpmbuild/SOURCES/amazon-efs-utils.tar.gz' | /usr/bin/tar -xvvf -
STATUS=$?
if [ $STATUS -ne 0 ]; then
  exit $STATUS
fi
cd 'amazon-efs-utils'
/usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .

**Comment by Cappuccinuo** [comment]
Hey @kunalgautam87 ,

What's the platform you are running the command? Can you share the ami id if possible as long as the full command you are running? Thanks.

**Comment by kunalgautam87** [comment]
Worked now. It was private ami (rhel 7.9)

**Comment by manisankar89** [comment]
can i know how you have solved the issue. i am facing the issue as 
make rpm
rm -rf build/rpmbuild
rm -rf amazon-efs-utils
rm -f amazon-efs-utils.tar.gz
mkdir -p amazon-efs-utils
mkdir -p amazon-efs-utils/dist
cp -p dist/amazon-efs-mount-watchdog.conf amazon-efs-utils/dist
cp: cannot stat ‘dist/amazon-efs-mount-watchdog.conf’: No such file or directory
make: *** [tarball] Error 1
