### ISSUE TITLE
brew can't find amazon-efs-utils

### ISSUE THREAD

**Issue by benlieb** [aws/efs-utils#113]
![image](https://user-images.githubusercontent.com/634562/144532447-4930abe6-0cd2-4cd9-be15-a60f0300f1f4.png)

Not sure what I'm missing. Granted I'm doing this on my local mac, not on an EC2 instance. Should that matter?

**Comment by gregmousseau** [comment]
+1

**Comment by gregmousseau** [comment]
I'm guessing b/c it's specific to Big Sur, and Monterey is out now, so likely an update coming?

**Comment by Cappuccinuo** [comment]
Thanks for the feedback. We'll have someone take a look, and get back to you when we have more information.

**Comment by JigarDedhia** [comment]
We support efs-utils only on EC2 based MacOS BigSur today. Local Macbooks are not supported.

**Comment by benlieb** [comment]
Maybe make a note in the docs (or make it more obvious) so people don't spin their wheels?

**Comment by Cappuccinuo** [comment]
https://github.com/aws/efs-utils#on-macos-big-sur-distribution We do have instruction on how to install efs-utils on MacOS, we mention `For EC2 Mac instances running macOS Big Sur`. I guess what you mean is make the `EC2` bold?

**Comment by benlieb** [comment]
That is far from clear from my point of view. Just because you can do something in one place doesn't mean you can't do it in another place. 

Could I suggest the following:

```
For EC2 Mac instances running macOS Big Sur, you can install amazon-efs-utils from the homebrew-aws respository. **Note that this will ONLY work on EC2 instances running macOS Big Sur, not on local Mac computers. **
```

**Comment by Cappuccinuo** [comment]
Thanks, LGTM, if you would like to submit a PR change, happy to review and merge it. Otherwise we will engage someone to change the language as you suggested.

**Comment by benlieb** [comment]
Tnx, unfortunately I don't have the time to make a PR atm. Hopefully someone else does!
