### ISSUE TITLE
Using EFS-UTILS on non ec2 machine for local development

### ISSUE THREAD

**Issue by ldm810** [aws/efs-utils#12]
I am dockerizing an application that utilizes the efs-utils to mount a directory in an app I am dockerizing.

Can you only use this on an ec2 machine that has access to an IAM role? Or can you provide the efs-utils with access keys on your local environment ?

**Comment by joetrav** [comment]
Hi ldm810,
You can build and install amazon-efs-utils on an on-premises host.  Please see https://docs.aws.amazon.com/efs/latest/ug/efs-onpremises.html for more details.

There are no dependencies on IAM roles at this time.  With amazon-efs-utils, there are not shared access keys to manage.  When using encryption of data in transit, we validate server authenticity using trusted certificates as part of the TLS protocol.  Can you elaborate on your question, and how you'd like to manage access keys for your use of amazon-efs-utils?

**Comment by ldm810** [comment]
Hi @joetrav thanks. I want to test my changes locally where I do not have access to Direct Connect.

Is it the case that to use amazon-efs-utils you either need to be running on an ec2 machine or need to use Direct Connect?

**Comment by ldm810** [comment]
Hey @joetrav just following up on this.
