### ISSUE TITLE
Failed to resolve DNS when mounting on-premises

### ISSUE THREAD

**Issue by robbinswill** [aws/efs-utils#120]
Hello, I'm running into an issue when trying to mount my EFS to my local machine. It seems like I've tried every option and am still getting stuck. My apologies if this is a very simple issue, I think I just need some direction on how to proceed.

When running the command:
```
sudo mount -t efs -o tls,accesspoint=<access point id> <file system id>: ~/efs
```
I receive the error:
```
Failed to resolve "<file system id>.efs.us-east-1.amazonaws.com". The file system mount target ip address cannot be found, please pass mount target ip address via mount options. 
Unable to locate credentials when performing operation DescribeMountTargets, please confirm your aws credentials are properly configured.
```

I've referenced the following documentation on mounting EFS:
https://docs.aws.amazon.com/efs/latest/ug/efs-mount-helper.html#mounting-access-points

So far I've tried mounting with Client VPN, IAM authorization and EFS access points with no success.

If anyone could help me with the above error it would be greatly appreciated as searches come up with little information. Alternatively, if you have a fool-proof method of mounting your EFS locally and would like to share the steps you take, I'm all ears.

If there's any additional info you need just let me know.

**Comment by Cappuccinuo** [comment]
Is that possible that you use `nslookup` to resolve the dns name of the file system to its mount target ip address? 

```bash
nslookup <file system id>.efs.us-east-1.amazonaws.com
```

For nslookup: https://linuxconfig.org/nslookup-linux-command

**Comment by robbinswill** [comment]
> Is that possible that you use `nslookup` to resolve the dns name of the file system to its mount target ip address?
> 
> ```shell
> nslookup <file system id>.efs.us-east-1.amazonaws.com
> ```
> 
> For nslookup: https://linuxconfig.org/nslookup-linux-command

```
nslookup <file system id>.efs.us-east-1.amazonaws.com
Server:         24.222.0.94
Address:        24.222.0.94#53

** server can't find <file system id>.efs.us-east-1.amazonaws.com: NXDOMAIN
```

Could this issue be related to my default VPC?

**Comment by robbinswill** [comment]
Sorry again, how do I ensure that my client instance (efs-utils?) is in the same VPC as my mount target?

I currently have one VPC (default) and when I created my EFS instance in the console I specified that default VPC to be the host. When I run ```aws configure list``` the access key and secret key are those associated with my IAM account that created the default VPC. All of the mount targets for the EFS instance are associated with the default VPC subnets.

**Comment by Cappuccinuo** [comment]
1. Suppose you have created an EC2 instance in `VPC-123456`, and the instance is in security group `sg-654321`
2. Suppose you create EFS via console, when it asks you to select Virtual Private Cloud, choose `VPC-123456`
3. Check the EFS you just created, in the Network section, make sure the mount target you created, is in the same VPC `VPC-123456` as your instance, and the security group is `sg-654321` as the instance.

**Comment by robbinswill** [comment]
I wasn't able to get it working. Not sure where to go from here. Still, thank you for your time and responses.

**Comment by lanxiudh** [comment]
I have the same problem.  
system:  aws EC2 ubuntu 22.04

when i run this steps below, i meet the same problem.  has been confirmed they are in the same VPC.

![image](https://github.com/user-attachments/assets/97e1e3d0-510a-4195-a934-f0506890c21c)

![1733402916713](https://github.com/user-attachments/assets/fc226f78-d125-4a5b-9938-1f1622011574)
