### ISSUE TITLE
Mounting an EFS volume on an actual macbook

### ISSUE THREAD

**Issue by Lionel-cl** [aws/efs-utils#122]
Sorry to ask this here.
But I really searched everywhere without finding a clear answer for how to do this. With or without EFS.
I think it would be very useful to add a few lines to your readme on the subject. Macos is Linux-based. However, in my case, it is impossible to mount an efs volume: error 72

**Comment by Cappuccinuo** [comment]
Hey,

Are you mounting on EC2 instance? As stated in our readme: https://github.com/aws/efs-utils#on-macos-big-sur-distribution, efs-utils ONLY work on EC2 instances running macOS Big Sur, not local Mac computers.

**Comment by Slooz** [comment]
I was able to use Docker to Direct Connect to EFS from my local MacBook:
```shell
$ docker build --tag efs - <<END
FROM amazonlinux
WORKDIR /root/
RUN \
  yum --assumeyes install amazon-efs-utils \
  && sed \
      --in-place \
      --null-data \
      's/\(#The region of the file system when mounting from on-premises or cross region.\n\)#region = us-east-1/\1region = us-east-2/' \
      /etc/amazon/efs/efs-utils.conf \
  && python3 -m pip install botocore
END
$ docker run \
  --rm \
  --cap-add SYS_ADMIN \
  --interactive \
  --tty \
  --mount type=bind,source="${HOME}"/.aws/,destination=/root/.aws/,readonly \
  efs
efs@ $ mount \
  --types efs \
  --options tls,iam \
  FILE_SYSTEM_ID \
  efs/
efs@ $ ls efs/
efs@ $ umount ~/efs/
efs@ $ exit
```

**Comment by dmackinn** [comment]
> I was able to use Docker to Direct Connect to EFS from my local MacBook:
> 
> $ docker build --tag efs - <<END
> FROM amazonlinux
> WORKDIR /root/
> RUN \
>   yum --assumeyes install amazon-efs-utils \
>   && sed \
>       --in-place \
>       --null-data \
>       's/\(#The region of the file system when mounting from on-premises or cross region.\n\)#region = us-east-1/\1region = us-east-2/' \
>       /etc/amazon/efs/efs-utils.conf \
>   && python3 -m pip install botocore
> END
> $ docker run \
>   --rm \
>   --cap-add SYS_ADMIN \
>   --interactive \
>   --tty \
>   --mount type=bind,source="${HOME}"/.aws/,destination=/root/.aws/,readonly \
>   efs
> efs@ $ mount \
>   --types efs \
>   --options tls,iam \
>   FILE_SYSTEM_ID \
>   efs/
> efs@ $ ls efs/
> efs@ $ umount ~/efs/
> efs@ $ exit

I've tried this method but I kept running up against `Could not start amazon-efs-mount-watchdog, unrecognized init system "bash"` wondering if you have any tips on how to get this working? Can I just add my remote IP to the SG or do I need to actually be on vpn?
