### ISSUE TITLE
test_tlsport debug logging fix

### ISSUE THREAD

**Issue by lt7** [aws/efs-utils#126]
Currently if debug logging is enabled, the test_tlsport function logs are displaying out of order

`mount.log:2022-03-28 09:58:50,921 - DEBUG - The tlsport 0.05 cannot be connected yet, sleep 20140(s), 5 retry time(s) left
mount.log:2022-03-28 09:58:50,929 - DEBUG - The tlsport 0.05 cannot be connected yet, sleep 20146(s), 5 retry time(s) left
mount.log:2022-03-28 09:58:50,931 - DEBUG - The tlsport 0.05 cannot be connected yet, sleep 20143(s), 5 retry time(s) left
mount.log:2022-03-28 09:58:50,933 - DEBUG - The tlsport 0.05 cannot be connected yet, sleep 20144(s), 5 retry time(s) left
mount.log:2022-03-28 09:58:50,954 - DEBUG - The tlsport 0.05 cannot be connected yet, sleep 20142(s), 5 retry time(s) left`

**Comment by Cappuccinuo** [comment]
@lt7 , thanks for the report.

Yes, I think the time and tlsport are logged in wrong places. Will fix this in next revision.
