### ISSUE TITLE
Use makedeb for Debian packaging

### ISSUE THREAD

**Issue by hwittenborn** [aws/efs-utils#128]
I saw that a manual script was being used for Debian packaging, and I though [makedeb](https://makedeb.org) (a personal project) could work well for the sake of uniformity and using a known packaging specification. It would also make it easier to package for [Arch Linux](https://archlinux.org), and both they and makedeb use pretty much the same packaging specification.

Would close #111.

**Comment by RyanStan** [comment]
This is a very cool! Thanks for bringing it up. I'll resolve this issue for now but I'm going to look into the tool some more.
