### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [aws/efs-utils#131]
Could you please consider to utilize built-in unittest.mock? I tested with python 3.8, and
```
sed -i 's:from mock:from unittest.mock:' test/*/test_*.py
```
did it for me. Background:
https://trello.com/c/S6eADbii/64-remove-python-mock
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by Cappuccinuo** [comment]
Thanks @pgajdos , thanks for calling this out. Will take a look.

**Comment by Cappuccinuo** [comment]
Updated in 1.33.1-1

**Comment by pgajdos** [comment]
Thanks!
