### ISSUE TITLE
The deprecation of Python version 3.6

### ISSUE THREAD

**Issue by osmin-lazo** [aws/efs-utils#133]
AWS is deprecating Python 3.6 for all services and "encouraging" updating to 3.8 or later but the efs-utils rpms building seem to be supported only up to 3.6.

**Comment by Cappuccinuo** [comment]
Hey @osmin-lazo ,

efs-utils supported python3.4+, are you saying you cannot use python 3.8 with efs-utils? Or you are saying efs-utils should enforce python dependency to 3.7+?

**Comment by osmin-lazo** [comment]
Hi,
I will dig to get more info but as is, I tried building/installing the rpms on a RHEL8 with Python 3.9 installed and it insisted in installing Python 3.6 as a dependency. For what is worth, on RHEL8 version 3.6 is installed as python3, 3.8 as python38 and 3.9 and python39

**Comment by Cappuccinuo** [comment]
I think this is due to https://github.com/aws/efs-utils/blob/master/amazon-efs-utils.spec#L12, we define we require python3 as dependency.

**Comment by osmin-lazo** [comment]
That makes sense, maybe it would be best to use the alternatives command?

# alternatives --set python /usr/bin/python3.9

I'll try modifying the spec file entry to the unversioned python and see if it works...

**Comment by osmin-lazo** [comment]
Found the reason:

$ cd efs-utils
$ make rpm
...
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-ldconfig
/sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile '' 1
+ /usr/lib/rpm/brp-python-hardlink
+ PYTHON3=/usr/libexec/platform-python
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
#mangling shebang in /usr/bin/amazon-efs-mount-watchdog from /usr/bin/env python3 to #!/usr/libexec/platform-python
#mangling shebang in /sbin/mount.efs from /usr/bin/env python3 to #!/usr/libexec/platform-python
...

Adding this to the spec file would avoid shebang mangling
%undefine __brp_mangle_shebangs

But other rpms required by efs-tools are probably also using the RH8 "platform-python" and so 3.6 is still being flagged as a dependency...

I guess we'll have to wait for RH to update their version of "platform-python".
