### ISSUE TITLE
Plugin "amazon-ecs-volume-plugin" not found

### ISSUE THREAD

**Issue by PGBI** [aws/efs-utils#134]
I'm trying to mount an EFS volume to an ECS task. The ECS cluster is composed of Ubuntu bionic EC2 instances. I've installed efs-utils on these Ubuntu ec2 instances using the Debian package installation type as described in the README.

After doing this, I'm not seeing the dreaded "container instance missing required attribute" anymore when the agent attempts to place an ECS task \o/

However, new tasks now fail to start with the following error:
```
Stopped reason
Error response from daemon: create xxx: error looking up volume plugin amazon-ecs-volume-plugin: plugin "amazon-ecs-volume-plugin" not found
```
Any guidance on how to get that plugin installed (or found?)

**Comment by lshigupt** [comment]
Thanks @PGBI  , Thanks for calling this out. Will take a look.

**Comment by PGBI** [comment]
Thanks @lshigupt for taking a look.

The recommended command fails:
```
$ sudo systemctl enable amazon-ecs-volume-plugin
Failed to enable unit: Unit file amazon-ecs-volume-plugin.service does not exist.
```
I had actually stumbled upon the reference doc you linked. It does explain how to enable the ECS volume plugin, but only for Amazon Linux 1 & 2 instances. It's not applicable for Ubuntu based instances.

**Comment by mythri-garaga** [comment]
Hi @PGBI,

May I know how the `amazon-ecs-init` is being installed on the instance?

For Ubuntu we have instructions here - 
1.  https://github.com/aws/amazon-ecs-init/tree/master/packaging/generic-deb/debian
or 
2. Pull latest amazon-ecs-init from s3 directly - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html

**Comment by PGBI** [comment]
We do not install `amazon-ecs-init` as explained in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-nonamazonlinux, we directly run the ecs agent by starting a container based on the https://hub.docker.com/r/amazon/amazon-ecs-agent docker image.

**Comment by mythri-garaga** [comment]
I see! We do not currently package `amazon-ecs-volume-plugin` outside of ecs-init. You would have to install `amazon-ecs-init` as mentioned in previously.

Please let us if you need any other details. Thank you.

**Comment by PGBI** [comment]
Alright, I pulled `amazon-ecs-init` from s3 and installed it, instead of running the agent using the amazon provided docker image and it fixed my issue.

Thanks a lot!
