### ISSUE TITLE
Look for efs_id for tag

### ISSUE THREAD

**Issue by gremila** [aws/efs-utils#141]
It could be very use full to have to ability to provide in the mount option a way to use efs tag to identify the EFS. Tha tcan help for region disaster recovery or after an EFS restore, This feature will avoid to change EC2 fstab configuration in the above case to mount the efs. 
With that for cross account efs no need of DNS which can cross the AZ between client and efs. So it can also help to have best latencies performance and decrease the cost in case of VPC peering.

I have try that in my fork and seems to works,

**Comment by RyanStan** [comment]
Thanks for the idea! The only problem I foresee is that tags aren't guaranteed to be unique, so we would possibly run into collisions when trying to find the EFS filesystem associated with a given tag.

Custom DNS names for your EFS filesystem may help this use case instead. That is a feature request which has been mentioned in other issues and is being tracked there.
