### ISSUE TITLE
macOS install of amazon-efs-utils using brew fails with pbr error

### ISSUE THREAD

**Issue by brujack** [aws/efs-utils#144]
==> Installing amazon-efs-utils from aws/aws
==> python3 -m venv --system-site-packages /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--atomicwrites-20221019-37687-nm1uew/atomicwrites-1.4.0
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--attrs-20221019-37687-dy4yiw/attrs-17.4.0
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--botocore-20221019-37687-1e203h8/botocore-1.17.53
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--configparser-20221019-37687-1tw5ind/configparser-3.5.0
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--coverage-20221019-37687-112cdcj/coverage-4.5.4
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--entrypoints-20221019-37687-14ri5j5/entrypoints-0.3
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--flake8-20221019-37687-1bbb9zj/flake8-3.7.9
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--funcsigs-20221019-37687-12k8ozb/funcsigs-1.0.2
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--jmespath-20221019-37687-qxknla/jmespath-0.10.0
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--mccabe-20221019-37687-wjjipd/mccabe-0.6.1
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--mock-20221019-37687-m8rp45/mock-2.0.0
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--more-itertools-20221019-37687-mr9wpz/more-itertools-8.6.
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--packaging-20221019-37687-gsv896/packaging-20.9
==> /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/amazon-efs-utils--pbr-20221019-37687-t2s5af/pbr-3.1.1
Last 15 lines from /Users/ec2-user/Library/Logs/Homebrew/amazon-efs-utils/15.pip:

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/private/tmp/amazon-efs-utils--pbr-20221019-37687-t2s5af/pbr-3.1.1/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /private/tmp/pip-record-ecaa4jaq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/Cellar/amazon-efs-utils/1.33.3/libexec/include/site/python3.10/pbr
  cwd: /private/tmp/amazon-efs-utils--pbr-20221019-37687-t2s5af/pbr-3.1.1/
  Running setup.py install for pbr: finished with status 'error'
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pbr

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python3.10 -m pip install --upgrade pip

Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by Cappuccinuo** [comment]
Does https://github.com/aws/homebrew-aws/commit/4188e19b486a9f59f7515ca515dc5f8f8684db25 this commit solve your problem?

**Comment by RyanStan** [comment]
The above commit should solve the problem.  This has been fixed.
