### ISSUE TITLE
release notes?

### ISSUE THREAD

**Issue by cmawhorter** [aws/efs-utils#152]
i've never had an issue with efs-utils before today when i noticed one server having a cpu spike and the reason seemed to be something related to efs. i'm trying to determine if i need to simply bump efs-utils or look more closely at the problem server.

from looking at the watchdog log, it seems like the tunnel disconnected, it tried to reconnect, and then logged an error repeatedly. something related to the ec2 IAM role along the lines or: `ValueError parsing b"__myEc2RoleName__" [...]`

release notes request somewhat related to #43

**Comment by RyanStan** [comment]
Release notes are currently in the package spec file, https://github.com/aws/efs-utils/blob/master/amazon-efs-utils.spec.  Thank you for the feedback, we'll track the release notes issue in #43, we've seen that this is something customers want.

If you're still running into your issue, feel free to open a new issue and we can work on resolution there.
