### ISSUE TITLE
Support for Rocky Linux 9.x

### ISSUE THREAD

**Issue by plaformsre** [aws/efs-utils#162]
Hi,

I would need to understand, if `efs-utils` are supported on Rocky Linux 9.x (https://rockylinux.org/download).

The README.md does not indicate any RHEL, CentOS 9.x OS is supported either.

Could you please clarify if it is supported and if not, what are the reasons?

Kind regards

**Comment by Ashley-wenyizha** [comment]
Hi @plaformsre 

Thanks for reaching out.

The list of verified supported Linux distributions is in README.md, for RHEL we do support RHEL 7 & RHEL 8, for CentOS, we have tested and verified CentOS 7 and CentOS 8, we have not yet tested and verified on CentOS9.

For other linux distributions, you can refer here for installation : https://github.com/aws/efs-utils#on-other-linux-distributions

Thanks
