### ISSUE TITLE
Missing Trusted Certificate

### ISSUE THREAD

**Issue by rickymulder** [aws/efs-utils#17]
I attempted to recreate the behavior of this tool by running a local stunnel and found that I was unable to verify each of the provided certs when connecting to my Amazon EFS endpoint.  stunnel was reporting the following:
```
2018.11.30 13:16:24 LOG4[17547:140558419277568]: CERT: Verification error: unable to get local issuer certificate
2018.11.30 13:16:24 LOG4[17547:140558419277568]: Certificate check failed: depth=3, /C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
2018.11.30 13:16:24 LOG7[17547:140558419277568]: SSL alert (write): fatal: unknown CA
2018.11.30 13:16:24 LOG3[17547:140558419277568]: SSL_connect: 14090086: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2018.11.30 13:16:24 LOG5[17547:140558419277568]: Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket
```

I copied the provided `efs-utils.crt` to my stunnel configuration and found it was missing the Starfield Services Root Certificate Authority - G2 cert.  I was forced to add https://certs.secureserver.net/repository/sf-class2-root.crt in order for stunnel to trust the provided CA certs and actually start using the stunnel `verify = 2` option.

I also setup efs-utils completely and found this cert was not needed for it's trust chain.

Please add this cert to your `efs-utils.crt`, or help explain why the efs-utils tool doesn't need this.

**Comment by jlluszcz** [comment]
Thanks for the feedback. We’ll have someone take a look and post a more detailed response once we better understand the issue.

**Comment by Cappuccinuo** [comment]
You can disable the cert check in this case via configuration file: https://github.com/aws/efs-utils/blob/master/dist/efs-utils.conf#L27, or pass the `cafile` option via mount options, the `efs-utils.crt` is a default one for general usecase of AWS EC2.
