### ISSUE TITLE
 install amazon-efs-utils on mac without using brew? 

### ISSUE THREAD

**Issue by owend-aim** [aws/efs-utils#170]
How can I install amazon-efs-utils on mac without using brew?  brew is not allowed by our security team.

**Comment by arnavgup1** [comment]
We currently do not support any other way to install amazon-efs-utils other than through homebrew for MacOS. However, if this is a highly requested feature, we will implement this and update this thread with any new information. Thanks for bringing this to our attention and we will keep this issue open for now to allow for other customers to +1 if they also would like this feature.
