### ISSUE TITLE
Official support for Ubuntu 22.04 on ARM64

### ISSUE THREAD

**Issue by Fydon** [aws/efs-utils#177]
I see that Circle CI is already [building for Ubuntu 22.04](https://github.com/aws/efs-utils/blob/71058a0fed32311e67403e18ca715d0283f94282/.circleci/config.yml#L195). However Ubuntu 20.04 is still the latest officially supported version according to the [README](https://github.com/aws/efs-utils/blob/71058a0fed32311e67403e18ca715d0283f94282/README.md?plain=1#L26) and [documentation](https://docs.aws.amazon.com/efs/latest/ug/manage-efs-utils-with-aws-sys-manager.html#sys-mgr-support-matrix). Also the AmazonEFSUtils Systems Manager Distributor doesn't support Ubuntu 22.04.

![image](https://github.com/aws/efs-utils/assets/3404761/4dd3eb4c-bd4c-4b76-ba73-108e4e096b9c)

I can't see an ARM64 builds in Circle CI, but the [documentation](https://docs.aws.amazon.com/efs/latest/ug/manage-efs-utils-with-aws-sys-manager.html#sys-mgr-support-matrix) states that ARM64 is supported on earlier Ubuntu releases using AmazonEFSUtils. Therefore I assume that once Ubuntu 22.04 is supported that it will also work on ARM64.

**Comment by Fydon** [comment]
Thank you. Ubuntu 22.04 appears to now be supported. However AWS Systems Manager installs something other than ARM64 (probably x64) on ARM64 instances.

![image](https://github.com/aws/efs-utils/assets/3404761/b9d2a6cc-fdd2-4a93-bb4e-44ee814bfcd4)

**Comment by anthotse** [comment]
We are aware of this issue. We're working on a new SSM distributor release to fix this.

**Comment by anthotse** [comment]
This is now resolved.
