### ISSUE TITLE
utcnow() deprecation warning under Python 3.12

### ISSUE THREAD

**Issue by major** [aws/efs-utils#187]
Fedora 39 has Python 3.12 and running the efs-utils watchdog causes the system journal to be filled with deprecation warnings:

```
/usr/bin/amazon-efs-mount-watchdog:2009: DeprecationWarning: datetime.datetime.utcnow()
is deprecated and scheduled for removal in a future version.
```

**Comment by bugfood** [comment]
I think that https://github.com/aws/efs-utils/pull/217 is correct for this.

**Comment by anthotse** [comment]
Use of `datetime.utcnow()` is removed in v2.0.3.
