### ISSUE TITLE
Additional Command Line Arguments Silently Break Encryption

### ISSUE THREAD

**Issue by eddieramirez** [aws/efs-utils#19]
additional command line arguments breaks the expected argument structure.

`sudo mount -v -t efs -o tls fs-25d214ac /efs`

yields the following sys.argv

`['/sbin/mount.efs', 'fs-25d214ac', '/efs', '-v', '-o', 'rw,tls’]`

the current code only looks for '-o' at index 3 and completely ignores the **tls** option and fails silently to use encryption in transit.

**Comment by eddieramirez** [comment]
#20

**Comment by jlluszcz** [comment]
Thanks for the feedback.  We’ll have someone take a look and post a more detailed response once we better understand the issue.

**Comment by patelia** [comment]
Corrected in PR #20, which has now been merged and released
