### ISSUE TITLE
./build-deb.sh: 33: cargo: not found

### ISSUE THREAD

**Issue by tubbink** [aws/efs-utils#208]
Hi there,

I'm encountering an issue where a manual install of the efs-utils following [this document](https://docs.aws.amazon.com/efs/latest/ug/installing-amazon-efs-utils.html#installing-other-distro) results in the error `./build-deb.sh: 33: cargo: not found`. The weird thing is that this has worked before. I'm running an instance with ubuntu-jammy-22.04-arm64-server-20231207. 

I'm executing:
```
apt install -y git binutils
git clone https://github.com/aws/efs-utils
cd efs-utils
./build-deb.sh
```

And get the following output from `./build-deb.sh`:
```
root@ip-10-100-172-220:/tmp/efs-utils# ./build-deb.sh
+ pwd
+ BASE_DIR=/tmp/efs-utils
+ BUILD_ROOT=/tmp/efs-utils/build/debbuild
+ VERSION=2.0.0
+ RELEASE=1
+ DEB_SYSTEM_RELEASE_PATH=/etc/os-release
+ echo Cleaning deb build workspace
Cleaning deb build workspace
+ rm -rf /tmp/efs-utils/build/debbuild
+ mkdir -p /tmp/efs-utils/build/debbuild
+ echo Creating application directories
Creating application directories
+ mkdir -p /tmp/efs-utils/build/debbuild/etc/amazon/efs
+ mkdir -p /tmp/efs-utils/build/debbuild/etc/init/
+ mkdir -p /tmp/efs-utils/build/debbuild/etc/systemd/system
+ mkdir -p /tmp/efs-utils/build/debbuild/sbin
+ mkdir -p /tmp/efs-utils/build/debbuild/usr/bin
+ mkdir -p /tmp/efs-utils/build/debbuild/var/log/amazon/efs
+ mkdir -p /tmp/efs-utils/build/debbuild/usr/share/man/man8
+ echo Building efs-proxy
Building efs-proxy
+ cd src/proxy
+ cargo build --release --manifest-path /tmp/efs-utils/src/proxy/Cargo.toml
./build-deb.sh: 33: cargo: not found
```

While the toml file is present:
```
root@ip-10-100-172-220:/tmp/efs-utils# ls -l /tmp/efs-utils/src/proxy/Cargo.toml
-rwxrwxrwx 1 root root 998 apr 23 12:52 /tmp/efs-utils/src/proxy/Cargo.toml
```

I've provided all users with all permissions on the efs-utils folder just to be sure.

What is going wrong here? Is this a bug? Am I doing something wrong?

**Comment by JC-WebFirst** [comment]
Starting v2.0 you need to add the rust and cargo as they are dependencies. 

`apt-get -y install git binutils rustc cargo pkg-config libssl-dev`

**Comment by justin-octo** [comment]
They are looking at removing the build and posting the artifacts in the repo.  Hope this is the path forward.  Build once for the repo instead of having to build each time you install.

**Comment by JC-WebFirst** [comment]
if you were previously using efs-util without issue, you can pin it to previous version and wait to upgrade to 2.0.0

`git clone --depth 1 --branch v1.36.0 https://github.com/aws/efs-utils`

**Comment by justin-octo** [comment]
Yeah, that's what I did.

**Comment by tubbink** [comment]
Thanks, that worked! Totally missed those dependencies

**Comment by tubbink** [comment]
Thanks, that worked! Totally missed those dependencies
