### ISSUE TITLE
timeout...

### ISSUE THREAD

**Issue by samoyedsun** [aws/efs-utils#22]
After installing amazon-efs-mount-watchdog, I execute the following command to mount it, and the result timeout occurs. Why?
```
[ec2-user@ip-172-31-25-116 ~]$ sudo mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-8139eac0.efs.ap-southeast-1.amazonaws.com:/test-efs1/ /mnt/efs1
mount.nfs: Connection timed out
```

**Comment by samoyedsun** [comment]
### Isn't ubuntu18.04 supported?



Distribution | Package Type | init System
-- | -- | --
Amazon Linux 2017.09 | rpm | upstart
Amazon Linux 2 | rpm | systemd
CentOS 7 | rpm | systemd
RHEL 7 | rpm | systemd
Debian 9 | deb | systemd
Ubuntu 16.04

**Comment by lilferna** [comment]
Could you please try mounting the file system with the following command, as per the EFS documentation (https://docs.aws.amazon.com/efs/latest/ug/mounting-fs.html):
```
sudo mount -t efs fs-8139eac0:/ /mnt/efs1
```
 
Thanks,
Lilian (EFS Team)

**Comment by Cappuccinuo** [comment]
Can you check the "File System Mount Hangs and Then Fails with Timeout Error" part in [this page](https://docs.aws.amazon.com/efs/latest/ug/troubleshooting-efs-mounting.html#mount-hangs-fails-timeout), timeout may caused by security group issue.

Thanks,
Yuan (EFS Team)

**Comment by Cappuccinuo** [comment]
> ### Isn't ubuntu18.04 supported?
> Distribution 	Package Type 	init System
> Amazon Linux 2017.09 	rpm 	upstart
> Amazon Linux 2 	rpm 	systemd
> CentOS 7 	rpm 	systemd
> RHEL 7 	rpm 	systemd
> Debian 9 	deb 	systemd
> Ubuntu 16.04

It is supported. Also Ubuntu 20.04 is supported now.

Please feel free to reopen this issue when encounter timeout again. Thanks.
