### ISSUE TITLE
Mounting EFS with TLS option from within a Docker container

### ISSUE THREAD

**Issue by jonfryd** [aws/efs-utils#23]
Hi guys,

I would like to mount an EFS volume over a TLS tunnel from a Java process running within a privileged Docker container. It does seem to work fine using the recommended `-o tls` option, but the `amazon-efs-mount-watchdog` fails to start with the following message:

`Could not start amazon-efs-mount-watchdog, unrecognized init system "java"`

I noticed during my initial testing that Java was unable to kill/destroy the `mount` process and hung forever (when I forgot to add the `--privileged` flag to `docker run`), which I suspect is also related to the watchdog not being launched.

Any tips/advice/help would be greatly appreciated.

Thank you.

**Comment by maxbecke** [comment]
Hey @jonfryd, we hook into init.d/systemd to manage the watchdog ([code](https://github.com/aws/efs-utils/blob/master/src/mount_efs/__init__.py#L365-L386)). There are associated configuration files for those two init systems in the [dist folder](https://github.com/aws/efs-utils/tree/master/dist).

I don't know how the default init system in Docker works, but I'm sure it'd require a code change in the linked method above to make it work unless you can somehow trick the container to think it's running with either init.d or systemd.

**Comment by jonfryd** [comment]
Hi @maxbecke, OK, thanks for your insights. Is there any significant risk in the watchdog not running? I suspect the watchdog is there for a good reason. 

From my testing so far everything has worked fine, but I've not experimented with jobs running more than ~30 minutes.

**Comment by maxbecke** [comment]
The watchdog is there to make sure that if the TLS relay process crashes that it gets re-started. The risk of not running the watchdog is that a crash in the TLS relay will cause your file system to become unavailable. The NFS client is connecting to the TLS relay directly, so, obviously, if that relay goes down the NFS client will get stuck trying to connect to something that isn't running.

**Comment by jonfryd** [comment]
OK, thanks. The relay (`stunnel` I believe) is able to handle transient errors (like temporary networking problems) gracefully, right?

**Comment by maxbecke** [comment]
Yeah we use `stunnel` as the TLS relay, and it is coded to handle netsplits gracefully. 

For more context the relay keeps the TCP state on "both sides" of itself in sync. It doesn't do any reconnecting itself and relies on the NFS client to see the termination and attempt a reconnect, which the NFS client does do.

**Comment by jonfryd** [comment]
Beautiful! Thanks a lot, @maxbecke.

**Comment by Fettah** [comment]
@jonfryd  how did you solve the issue here ?

**Comment by jonfryd** [comment]
> @jonfryd how did you solve the issue here ?

By simply ignoring the message and not running any watchdog. `stunnel` seems rock solid and so far we haven't had any issues.
