### ISSUE TITLE
you broke efs yesterday

### ISSUE THREAD

**Issue by steveheistand** [aws/efs-utils#244]
mount.efs (possibly others) have lines in them that arent python code:
for example

<<<<<<< HEAD
        dns_name_suffix = get_target_domain_suffix(config)
=======
>>>>>>> upstream/master

**Comment by evannorstrand-mp** [comment]
Confirmed, this is breaking anyone pulling from master.

**Comment by ahmedhosny** [comment]
yup...

**Comment by dlm6693** [comment]
This needs to be fixed yesterday can someone address this asap?

**Comment by Glenn-Duffy-Bose** [comment]
@seanzatzdev-amazon @jdwtf ☝️

**Comment by seanzatzdev-amazon** [comment]
Reverted the changes here https://github.com/aws/efs-utils/pull/245

**Comment by Glenn-Duffy-Bose** [comment]
Thank you @seanzatzdev-amazon
