### ISSUE TITLE
Inconsistency between RPM and DEB build architectures?

### ISSUE THREAD

**Issue by dgersting** [aws/efs-utils#251]
I might be mistaken, but I feel there's an inconsistency between the RPM and DEB build architectures.

**For RPM builds:**
https://github.com/aws/efs-utils/blob/87874bd1a18a262fdcb1264f9bc0b8e4b8a77bd6/amazon-efs-utils.spec#L52

**For DEB builds:**
https://github.com/aws/efs-utils/blob/87874bd1a18a262fdcb1264f9bc0b8e4b8a77bd6/dist/amazon-efs-utils.control#L2

Since efs-utils is compiled w/ Rust, wouldn't the DEB build need to target specific architectures as `all` would "indicate an architecture-independent package" based on the Debian control file spec?

References:
- https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-architecture

**Comment by dgersting** [comment]
Oh, I just noticed there's an open pull request from April which addresses this very issue: https://github.com/aws/efs-utils/pull/211

**Comment by anthotse** [comment]
We've merged in #211. This is now fixed.
