### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by lisenet** [aws/efs-utils#253]
Hello there, is there a changelog available for efs-utils releases?

**Comment by dgersting** [comment]
Only one I'm aware of is in the RPM spec file: https://github.com/aws/efs-utils/blob/master/amazon-efs-utils.spec#L194

**Comment by dgersting** [comment]
The only one I'm aware of is in the RPM spec file:
https://github.com/aws/efs-utils/blob/master/amazon-efs-utils.spec#L194

**Comment by lisenet** [comment]
That is useful, thank you. So if I understand it right, the addition of new ISO regions to config file resulted in a minor release instead of a patch one.
