### ISSUE TITLE
Question on data-in-transit encryption

### ISSUE THREAD

**Issue by jerisalan** [aws/efs-utils#256]
Had a question primarily on data-in-transit encryption with respect to AWS EFS usage.

We have a lot of EC2 instances and an AWS EFS instance created within the same AWS VPC. The AWS EFS has multiple access points created which are all mounted onto the EC2 instances. We use AWS `efs-utils` utility for mounting EFS onto EC2 instances extensively and primarily use it because it provides data in transit encryption support via stunnel. Over the course of the last few years, we have begun noticing issues where the NFS server does not respond at times and the mounting times out causing application hangs and other cascading issues. 

We are considering switching from using the aws-efs-utils tool to the standard mount command without the IAM option. 

```
sudo mount -t efs -o tls,iam,accesspoint=access-point-id file-system-id efs-mount-point/

to

sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport <file-system-id>.efs.<region>.amazonaws.com:/ efs
```
My question is will switching to the latter mean we lose TLS 1.2 data-in-transit encryption? Does AWS auto encrypt or not auto-encrypt all network within a VPC...in this case b/w EFS server and EC2 instances?

**Comment by DoobleD** [comment]
Not sure about the switching question, but regarding VPC, my understanding is that within a VPC data in transit cannot be sniffed, apart from an AWS employee physically inside the AZ.

See the following resources on the subject:
- https://www.reddit.com/r/aws/comments/jfzjmr/comment/g9p1891/
- https://www.reddit.com/r/aws/comments/jfzjmr/comment/g9np84o/
- https://kevin.burke.dev/kevin/aws-alb-validation-tls-reply/
- https://news.ycombinator.com/item?id=23033539
- https://x.com/0xdabbad00/status/995833462660612096

**Comment by anthotse** [comment]
> My question is will switching to the latter mean we lose TLS 1.2 data-in-transit encryption?

Yes, mounting with `mount -t nfs4` will mean that the data in transit will not be encrypted.

> Does AWS auto encrypt or not auto-encrypt all network within a VPC...in this case b/w EFS server and EC2 instances?

No, AWS does not automatically encrypt traffic.
