### ISSUE TITLE
Failed to initialize TLS tunnel

### ISSUE THREAD

**Issue by Zyles** [aws/efs-utils#27]
Doesn't work under Ubuntu 18.04.

Even compiled latest stunnel and your efs utils.

Can you at least put some effort into supporting the biggest distros in your cloud and not just Amazon AMI.

That would be fantastic.

Oh, and update your docs. They are out of date and you wasted approximately 5 hours of my time.

**Comment by patelia** [comment]
Hi Zyles,
 
Can you share the AMI ID you used, the steps that you tried, and issues you encountered along the way? If you have the exact commands you ran and their output, that information would be helpful.
 
Our recommended workflow for installing efs-utils on Ubuntu is:
```
git clone https://github.com/aws/efs-utils
cd efs-utils/
sudo apt-get update
sudo apt-get -y install binutils
./build-deb.sh
sudo apt-get -y install ./build/amazon-efs-utils*deb
```

An EFS file system can then be mounted with:
```
sudo mount -t efs -o tls <fs_id, e.g. fs-12345678> /mnt
```

We are able to run this without issue on Ubuntu 18.04 in our own environments. Does this workflow succeed for you?  Can you clarify which documentation page you followed that caused difficulty for you?

**Comment by Zyles** [comment]
I used the official Ubuntu 18.04, not sure what AMI it was.

I tried it again and now it seems to work with some extra configs.

I did what you suggested and it is also here:
https://docs.aws.amazon.com/efs/latest/ug/using-amazon-efs-utils.html

But then I also need to change the region because it is a cross region request:
https://docs.aws.amazon.com/efs/latest/ug/efs-different-vpc.html

The line in docs points to `/etc/amazon/efs/amazon-efs-utils.conf` which is incorrect. On my install it is ` /etc/amazon/efs/efs-utils.conf`

Now it fails to resolve so I also need to also edit the hosts file:
<mount target ip> fs-123456789.efs.eu-central-1.amazonaws.com

Then I can mount it.

However... the docs need the mention of having to upgrade stunnel which apparently seems optional on Ubuntu now that I tried without updating it. So if I do that with the latest version I get this problem.

I compile the latest stunnel version.

When I try to mount I get the error: `Failed to initialize TLS tunnel` even if I put `stunnel_check_cert_hostname = false` and `stunnel_check_cert_validity = false`

So I have to downgrade stunnel again with apt-get.

**Comment by patelia** [comment]
> The line in docs points to `/etc/amazon/efs/amazon-efs-utils.conf` which is incorrect. On my install it is `/etc/amazon/efs/efs-utils.conf`

You are correct, that is an error in our documentation. We will update our docs accordingly. 

The docs suggest upgrading stunnel if the application is old and lacking certain functionality that is required for the EFS mount helper. Specifically, stunnel needs to support the `OCSPaia` and `checkHost` options. The stunnel version that ships with Ubuntu 18.04, stunnel v5.44, supports both of these options, so no upgrade is necessary on Ubuntu. 

As for why mounts failed when you installed the latest stunnel version, I cannot say for sure without more information. You can turn on stunnel logs in `/etc/amazon/efs/efs-utils.conf` by setting `stunnel_debug_enabled = true`, and stunnel logs will be generated for all future mount attempts. Check the stunnel logs in `/var/log/amazon/efs` to determine why stunnel failed to initialize. Do note that stunnel logs can consume a nontrivial space on your instance if the config option is left enabled.

**Comment by Zyles** [comment]
I just used 5.44 instead and it works now. Don't really want to spend time debugging stunnel.

Thanks.
