### ISSUE TITLE
mount.efs --version show incorrect version number

### ISSUE THREAD

**Issue by glaubitz** [aws/efs-utils#36]
I just packaged ```efs-utils``` 1.16 for openSUSE/SLE and while performing some basic tests I noticed that ```mount.efs --version``` returns the version number 1.13:

```
suse-laptop:~ # mount.efs --version
/sbin/mount.efs Version: 1.13
suse-laptop:~ #
```

**Comment by maxbecke** [comment]
Fixed in c7a4b968b8e6ce8894abb64029e519580fa96e42. 
See #24 for context.
