### ISSUE TITLE
Incorrect DNS name for EFS filesystem in China region

### ISSUE THREAD

**Issue by linjungz** [aws/efs-utils#38]
EFS mount helper uses an incorrect DNS name for filesystem and leads to error when mounting filesystem:

```
[ec2-user@ip-172-31-40-70 ~]$ sudo mount -t efs fs-bd02e558:/ efs 
Failed to resolve "fs-bd02e558.efs.cn-northwest-1.amazonaws.com (http://fs-bd02e558.efs.cn-northwest-1.amazonaws.com/)" - check that your file system ID is correct. 
See https://docs.aws.amazon.com/console/efs/mount-dns-name for more detail. 

[ec2-user@ip-172-31-40-70 ~]$ sudo mount -t efs -o tls fs-bd02e558:/ efs 
Failed to resolve "fs-bd02e558.efs.cn-northwest-1.amazonaws.com (http://fs-bd02e558.efs.cn-northwest-1.amazonaws.com/)" - check that your file system ID is correct. 
See https://docs.aws.amazon.com/console/efs/mount-dns-name for more detail.
```
correct DNS name should be ended with efs.Region.amazonaws.com.cn
currently we can only mount efs filesystem using NFS client, not EFS mount helper from efs-utils

When correcting the DNS name, we could use NFS client to mount filesystem:

`[ec2-user@ip-172-31-40-70 ~]$ sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-bd02e558.efs.cn-northwest-1.amazonaws.com.cn:/ efs`

I checked the source file and maybe we should determine whether it's running in commercial region or China region so that the mount helper could use the correct DNS name:

https://github.com/aws/efs-utils/blob/master/src/mount_efs/__init__.py
line 133: 

`EFS_FQDN_RE = re.compile(r'^(?P<fs_id>fs-[0-9a-f]+)\.efs\.(?P<region>[a-z0-9-]+)\.amazonaws.com$') `

Could you please kindly help to resolve this issue? Thanks a lot!

**Comment by Cappuccinuo** [comment]
Hi @linjungz, thank you for your feedback. Could you please share your linux distribution as well as mount.efs version by running ```mount.efs --version```? Thanks.

**Comment by linjungz** [comment]
I'm using efs mount helper in a EC2 instance using Amazon Linux 2.
Here's the mount.efs version:
```
mount.efs --version
/usr/sbin/mount.efs Version: 1.18
```
And here's the workaround for China region as documented:
https://docs.amazonaws.cn/en_us/efs/latest/ug/mounting-fs.html

`echo -e '\n[mount.cn-north-1]\ndns_name_suffix = amazonaws.com.cn\n\n[mount.cn-northwest-1]\ndns_name_suffix = amazonaws.com.cn' \| sudo tee -a /etc/amazon/efs/efs-utils.conf`



But I'm afraid we need to add more hints in the console to direct to the documentation. Otherwise the user would get very confused.

**Comment by Cappuccinuo** [comment]
Thank you for your feedback and suggestion linjungz@.

We have recently updated our efs-utils to [v1.19](https://github.com/aws/efs-utils/releases/tag/v1.19) to support China region. Could you please run the following command to update the tool?

```bash
git clone https://github.com/aws/efs-utils
cd efs-utils
sudo yum -y install rpm-build
make rpm
sudo yum -y install build/amazon-efs-utils*rpm
```

Checking the version again by running `mount.efs --version`, the version should be 1.19 now.

We will figure out a better way to send this hint to user before our package is fully built and update in Amazon Linux. Let we know if you have any other issue or concern.

**Comment by linjungz** [comment]
Thank you for the information @Cappuccinuo 
I suggest we push the update to Amazon Linux repository as soon as possible.

**Comment by Cappuccinuo** [comment]
@linjungz We will. Thanks again for your feedback.
