### ISSUE TITLE
efs-utils seems to be unable to deal with IMDSv2

### ISSUE THREAD

**Issue by mdmallardi** [aws/efs-utils#40]
Hi all, in my organization, we have switched to IMDSv2 by setting http-tokens to required in the instance metadata service for every instance.  efs-utils fails to mount once this has been set as it reports 'Error retrieving region'

Any help would be appreciated. (I'm using a build based on commit d692ffe1deac2a900424a7402643ee7a16d5ca92 currently)

**Comment by lilferna** [comment]
Thanks for the feedback. We’ll have someone take a look and post a more detailed response once we better understand the issue.

**Comment by Cappuccinuo** [comment]
Hey @mdmallardi ,

Thanks for your feedback!

IMDSv2 is a new metadata service released in Nov.2019, currently we retrieve ec2 instance metadata using IMDSv1. 

I can reproduce this issue and we are working on it to support IMDSv2.

Can you share with me the following information:

1. **The method you use to enable IMDSv2 on instance**
For me, I am using 
```bash
aws ec2 modify-instance-metadata-options  --instance-ids $INSTANCE_ID --profile $PROFILE --http-endpoint enabled --http-token required
```
2. **If you can see valid result after running [following command](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html) on your instance**
```bash
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" –v http://169.254.169.254/latest/dynamic/instance-identity/document
```

Thanks.

**Comment by mdmallardi** [comment]
I am using the same command to activate IMDSv2, and get a correct response using the command you posted.

**Comment by Cappuccinuo** [comment]
Great, thanks for your reply.

The workaround solution I provide to you before we fix it is:

1. check the `region` value you get from that command, e.g. us-east-1
2. modify /etc/amazon/efs/efs-utils.conf dns_name_format by running
```bash
# your region, e.g. us-east-1
$ REGION=
```
```bash
$ sudo sed -i "s/{region}/$REGION/" /etc/amazon/efs/efs-utils.conf
```
This will change 
```bash
dns_name_format = {fs_id}.efs.{region}.{dns_name_suffix}
```
to 
```bash
dns_name_format = {fs_id}.efs.us-east-1.{dns_name_suffix}
```
This way we won't retrieve the region using ec2 metadata service for now.

**Comment by Cappuccinuo** [comment]
@mdmallardi Could you please try the [latest release](https://github.com/aws/efs-utils/releases/tag/v1.22)? Thanks.

**Comment by mdmallardi** [comment]
This has been tested, and works! (v1.22-1)  Thanks so much for a quick resolution to this!
