### ISSUE TITLE
Mounting EFS inside Docker container not responding

### ISSUE THREAD

**Issue by k-toda** [aws/efs-utils#46]
I executed 
> mount -t efs $EFS_DOMAIN:/ /mnt/efs

with version 1.23-2 then hunged.

With version 1.21-2, mount was succeeded.

I tried below commands in container. And 

> curl http://169.254.169.254/latest/meta-data/

is OK.

> curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"

does not respond.

I think this is the cause of the issue.

**Comment by Cappuccinuo** [comment]
Hey @k-toda , thanks for reporting this issue.

Could you please share with us your linux distribution, docker version, as well as awscli version(aws --version)?

To solve this issue for now, you can do the following steps:

1. Download and install latest v1.24 efs-utils through Github
```bash
$ sudo yum -y install git rpm-build make
$ git clone https://github.com/aws/efs-utils
$ cd efs-utils
$ make rpm
$ sudo yum -y install build/amazon-efs-utils*rpm
```
2. Modify efs-utils.conf located in /etc/amazon/efs/, change the region in https://github.com/aws/efs-utils/blob/master/dist/efs-utils.conf#L20 to your instance region, which can be accessed by `curl http://169.254.169.254/latest/meta-data/`, and un-comment that line
3. Mount again.

**Comment by Cappuccinuo** [comment]
Ignore the aws version, seems unrelated. 

Can you get any output after executing below command on your instance?

```bash
curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"
```

**Comment by k-toda** [comment]
@Cappuccinuo 
Thank you for replying. My workaround is fixing version to 1.21-2.

>  linux distribution

Amazon Linux release 2 (Karoo)

> docker version

Docker version 18.09.9-ce, build 039a7df

> Can you get any output after executing below command on your instance?

Curl on ECS instance returns token properly.

**Comment by auzroz** [comment]
We are running into this as well. Using 1.24 inside amazonlinux:latest container results in an overall hang of the process during mount. Reverting to 1.23 had the same behavior, revering to 1.21 resolved the issue.

**Comment by Cappuccinuo** [comment]
@auzroz Are you using efs-utils v1.24-4? If not, could you please pull the latest Github package and build? The yum repo is not updated yet.

**Comment by auzroz** [comment]
I'll give it a shot, standby.
