### ISSUE TITLE
Support for SUSE Linux Enterprise Server

### ISSUE THREAD

**Issue by mpata** [aws/efs-utils#51]
Hi,

Would it be possible to add openSUSE/SLES as a verified distribution?
All the tests run successfully and usage seems to work fine.

Thanks.

**Comment by lilferna** [comment]
Thanks for the feedback. We’ll have someone take a look and post a more detailed response once we better understand the issue.

**Comment by Cappuccinuo** [comment]
Hi @mpata ,

Thanks for the feedback.

Could you please check if following command is correct for installing amazon-efs-utils on OpenSUSE:

```bash
sudo zypper install -y git rpm-build make
git clone https://github.com/aws/efs-utils
cd efs-utils
make rpm
sudo zypper install -y --allow-unsigned-rpm build/amazon-efs-utils*rpm
```

**Comment by mpata** [comment]
Hi @Cappuccinuo,

Unfortunately with the latest AMI provided by openSUSE, openSUSE-Leap-15-1-v20190702-hvm-ssd-x86_64 (ami-0f81506cab2b62029 @ eu-west-1), there's a dependency conflict in *rpm-build*.
You'll either have to uninstall *gettext-runtime-mini-0.19.8.1-lp151.4.50.x86_64* or ignore the *gettext-tools* dependency.

Either way, *rpm-build* is able to build a proper package for *efs-utils* and it installs correctly on the system.

The first instruction that you provided won't work out-of-the-box on openSUSE 15.1, but apart from that everything's good. Just remove the *-y* flag and let the user decide what to do.

**Comment by thimslugga** [comment]
The efs-utils are available in the SLES Public Cloud repos and have been for some time.

```
$ zypper info aws-efs-utils

# SLES 15
Information for package aws-efs-utils:
--------------------------------------
Repository     : SLE-Module-Public-Cloud15-SP1-Pool
Name           : aws-efs-utils
Version        : 1.7-1.3.1
Arch           : noarch
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3
Installed Size : 44.7 KiB
Installed      : No
Status         : not installed
Source package : aws-efs-utils-1.7-1.3.1.src
Summary        : Utilities for using the EFS file systems
Description    :
    This package provides utilities for using the EFS file systems.

# SLES 12
Information for package aws-efs-utils:
--------------------------------------
Repository     : SLE-Module-Public-Cloud12-Updates
Name           : aws-efs-utils
Version        : 1.7-1.3.1
Arch           : noarch
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3
Installed Size : 44.7 KiB
Installed      : Yes
Status         : up-to-date
Source package : aws-efs-utils-1.7-1.3.1.src
Summary        : Utilities for using the EFS file systems
Description    :
    This package provides ut

$ zypper in -y aws-efs-utils

$ rpm -ql aws-efs-utils
/etc/amazon
/etc/amazon/efs
/etc/amazon/efs/efs-utils.conf
/etc/amazon/efs/efs-utils.crt
/sbin/mount.efs
/usr/bin/amazon-efs-mount-watchdog
/usr/lib/systemd/system/amazon-efs-mount-watchdog.service
/usr/sbin/rcamazon-efs-mount-watchdog
/usr/share/doc/packages/aws-efs-utils
/usr/share/doc/packages/aws-efs-utils/NOTICE
/usr/share/doc/packages/aws-efs-utils/README.md
/usr/share/licenses/aws-efs-utils
/usr/share/licenses/aws-efs-utils/LICENSE
/usr/share/man/man8/mount.efs.8.gz
/var/log/amazon
/var/log/amazon/efs
```

* https://www.suse.com/support/update/announcement/2019/suse-ru-20191146-1/
* https://build.opensuse.org/package/show/Cloud:Tools/aws-efs-utils
