### ISSUE TITLE
support for web identity

### ISSUE THREAD

**Issue by rajatjindal** [aws/efs-utils#54]
we are trying to use EFS provisioner on our k8s cluster, and it seems that we can not use web identity based token using this.

https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

is this something that is planned for efs-utils?

many thanks

**Comment by Cappuccinuo** [comment]
Hey @rajatjindal , thanks for the feedback,

Can you share with us

1. The EFS provisioner you use
2. Detail steps to use this web-identity with EFS, and what is the error? 

Thanks

**Comment by rajatjindal** [comment]
Hi @Cappuccinuo ,

thanks for replying.

- we are using official EFS provisioner https://github.com/kubernetes-sigs/aws-efs-csi-driver
- using web-identity based credentials, you can get session tokens automatically (its supported by all AWS sdk. e.g. https://github.com/boto/botocore/blob/9f5afe26cc4a2695dcb62db453f9db7c299f3ffc/botocore/credentials.py#L1615

If my understanding is correct, the efs-utils actually takes care of getting the session token (if we provide tls,iam mount options).

and if I read the code correctly, efs-utils do not use AWS sdk as such and therefore support only a subset of credential providers. 

Possibly we should start using AWS sdk for efs-utils, and that will automatically add support for Web Identity provider.
