### ISSUE TITLE
Is amazon-ssm-agent required for efs-utils to work?

### ISSUE THREAD

**Issue by alfredocambera** [aws/efs-utils#56]
I'm getting the following error message:

INFO Entering SSM Agent hibernate - AccessDeniedException: User: arn:aws:sts::ABCDEFGHIJK:assumed-role/group/i-00a457c44cf7c1e42 is not authorized to perform: ssm:UpdateInstanceInformation on resource: arn:aws:ec2:us-west-2:ABCDEFGHIJK:instance/iadsfadsfa

I see that the amazon-ssm-agent is installed by default. Do I need to add the required role to the EC2 so I don't get this error message to make the app work fine?

I could not find any reference about `amazon-ssm-agent`  in the README.md file

**Comment by Cappuccinuo** [comment]
Hey @alfredocambera ,

Could you please share your linux distribution, and what command you are running? 

Also can you share your efs-utils version? `mount.efs --version`

**Comment by alfredocambera** [comment]
This is what I got from journalctl:

```
Apr 16 04:05:44 ip-10-1-1 amazon-ssm-agent.amazon-ssm-agent[1009]: 2020-04-16 04:05:44 INFO Backing off health check to every 3600 seconds for 10800 seconds.
Apr 16 04:05:44 ip-10-1-1 amazon-ssm-agent.amazon-ssm-agent[1009]: 2020-04-16 04:05:44 ERROR Health ping failed with error - AccessDeniedException: User: arn:aws:sts::123123123123:assumed-role/name-of-the-role/i-12341234124 is not authorized to perform: ssm:UpdateInstanceInformation on resource: arn:aws:ec2:us-west-1:123123123123:instance/i-123412341234
Apr 16 04:05:44 ip-10-1-1 amazon-ssm-agent.amazon-ssm-agent[1009]:         status code: 400, request id: 372013da-2159-47a9-89be-dc21062f6949
```

```
root@ip-10-1-1:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

```
root@ip-10-1-1:~# mount.efs --version
/sbin/mount.efs Version: 1.25
```

**Comment by alfredocambera** [comment]
Here is the amazon-ssm service:

```
root@ip-10-1-1:~# systemctl --type=service |grep amazon-ssm
snap.amazon-ssm-agent.amazon-ssm-agent.service loaded active running Service for snap application amazon-ssm-agent.amazon-ssm-agent
```

**Comment by Cappuccinuo** [comment]
@alfredocambera 

We don't rely on ssm agent. Is there any issue when you mount with efs-utils? 

For issue related to ssm agent, you may post to https://github.com/aws/amazon-ssm-agent.

Thanks.

**Comment by alfredocambera** [comment]
You are right. I double checked and the issue I'm having is related to something else.
