### ISSUE TITLE
Drop mandatory use of Python2

### ISSUE THREAD

**Issue by jsf9k** [aws/efs-utils#57]
Python2 is already EOL, and Python2 libs are already starting to disappear from, e.g., Debian Bullseye.  I realize that the code in this project supports Python3, but please consider adding packaging support for Python 3, at least for some versions of distributions.

I'm not sure the best way to go about this, but here are some places that I think would need to be changed:
* The code [here](https://github.com/aws/efs-utils/blob/master/mangle-shebangs.sh) explicitly forces Python2 for *all* versions of Fedora.
* The code [here](https://github.com/aws/efs-utils/blob/master/dist/amazon-efs-utils.control#L5) forces Python2 as a dependency for any Debian packages that are built.
* The code [here](https://github.com/aws/efs-utils/blob/master/dist/amazon-efs-utils.spec#L13) forces Python2 as a dependency for any RPMs packages that are built.

**Comment by Cappuccinuo** [comment]
Hey @jsf9k ,

Can you try the latest code?

Thanks.

**Comment by jsf9k** [comment]
@Cappuccinuo thank you very much for making that change.  I do have a couple of thoughts.

1. The [current solution](https://github.com/aws/efs-utils/blob/master/build-deb.sh#L17-L18) handles the Debian 11 case, for example, but not future versions of that distribution.  Is there a way to change the regexes so that they match on Ubuntu 18 and higher, and Debian 11 and higher?  Some "future-proofing" seems like a good idea here, so you don't have to continually modify the regexes 
2. This "for which distributions do I use python2 and for which do I use python3?" problem plagues Ansible as well.  In Ansible, [if you set `ansible_python_interpreter=auto`](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml#L1450-L1468) (which will soon to be the default behavior anyway) then [this internal map](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml#L1469-L1484) is used to determine which version of python to use.  (If the distro doesn't match any in the map, then [this list of python versions](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml#L1487-L1498) is followed until an interpreter is found.)  What do you think of following Ansible's lead and using python3 for Debian 10+, Fedora 23+, Ubuntu 16+, etc.?  Just a thought.

**Comment by Cappuccinuo** [comment]
Hey @jsf9k ,

1. I update the python3 dependency [here](https://github.com/aws/efs-utils/blob/master/build-deb.sh#L36)
2. I was thinking this problem also. With more and more distributions introduced, one thought is we have python3 as default interpreter and dependency, the regex here will be changed to the distributions that do not use python3 as default.
3. This is a very good example, I will take a look at it. Currently our thought is, for the distribution that does not use python3 as default, we still keep python2 as default dependency.

**Comment by jsf9k** [comment]
> Hey @jsf9k ,
> 
> 1. I update the python3 dependency [here](https://github.com/aws/efs-utils/blob/master/build-deb.sh#L36)
> 2. I was thinking this problem also. With more and more distributions introduced, one thought is we have python3 as default interpreter and dependency, the regex here will be changed to the distributions that do not use python3 as default.
> 3. This is a very good example, I will take a look at it. Currently our thought is, for the distribution that does not use python3 as default, we still keep python2 as default dependency.

1. Ah!  Sorry I missed that.
1. I like this idea, and I think it is probably simpler than doing it the other way around.  Python2 is end-of-life at this point, so it makes a lot of sense to me.
1. :+1:
