### ISSUE TITLE
RHEL8 workaround should be applied to CentOS 8

### ISSUE THREAD

**Issue by scantor** [aws/efs-utils#58]
There's a workaround guarding an unsupported option:

    if RHEL8_RELEASE_NAME not in get_system_release_version():
        efs_config['libwrap'] = 'no'

This is happening on CentOS 8 because the condition apparently evals to true, so the option's getting passed in and causing the TLS connection set up to fail. The log mentions stunnel not supporting libwrap based on what I'm seeing. Commenting out the condition entirely on 8 is resulting in success, so the fix is probably just to expand that conditional.

**Comment by Cappuccinuo** [comment]
Thanks for the feedback. 

RHEL8 and CentOS8 should have the same issue for stunnel that they don't support libwrap. Currently please use the workaround solution that is commenting out this condition, I'll take a look at this issue. Thanks.
