### ISSUE TITLE
incorrect version of debian-package 

### ISSUE THREAD

**Issue by PhilSwiss** [aws/efs-utils#59]
the release **1.25-2** - https://github.com/aws/efs-utils/releases/tag/v1.25-2
and the release **1.25-1** - https://github.com/aws/efs-utils/releases/tag/v1.25-1

have the exact same version (**1.25**) for the debian-package in **dist/amazon-efs-utils.control**, see:
https://github.com/aws/efs-utils/blob/master/dist/amazon-efs-utils.control

when you build a debian-package with **build-deb.sh** both will have the exact same version (**1.25**)
in the end. 

![aws-efs-utils](https://user-images.githubusercontent.com/46283819/81944516-277d2980-95fd-11ea-9162-03c2ed852e58.png)

So it is not possible to update **amazon-efs-utils-1.25-1.deb** with **amazon-efs-utils-1.25-2.deb** because **apt** assumes the version is **already installed**.

The following files are also affected: "config.ini", "dist/amazon-efs-utils.spec", "src/watchdog/__init__.py" and "src/mount_efs/__init__.py"

Possible fixes for the future may be:
- new versioning with: Major.Minor-Release
or
- old versioning with: Major.Minor (even for small releases/fixes)

Would be happy for a fixed versioning, thanks alot.

**Comment by Cappuccinuo** [comment]
@PhilSwiss , We use `Major.Minor-Release` across the package in the commit I referenced, thanks for your feedback.
