### ISSUE TITLE
Non-ASCII characters in dist/efs-utils.conf cause mount issues

### ISSUE THREAD

**Issue by mark-sinclair** [aws/efs-utils#66]
Running the following on a fresh Ubuntu 18.04 base AMI on EC2:

```apt -y update
apt -y upgrade
apt -y install binutils

git clone https://github.com/aws/efs-utils
cd efs-utils || exit
./build-deb.sh
apt -y install ./build/amazon-efs-utils*deb
cd .. || exit

mount -t efs -o tls,iam "${efs_volume}" "${efs_mount_target}"
```
I get the following error:

```
Traceback (most recent call last):
  File "/sbin/mount.efs", line 1577, in <module>
    main()
  File "/sbin/mount.efs", line 1556, in main
    config = read_config()
  File "/sbin/mount.efs", line 1217, in read_config
    p.read(config_file)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 867: ordinal not in range(128)
```

This seems to be related to a hidden non-ASCII character in line 26 of `dist/efs-utils.conf` (which gets installed to `/etc/amazon/efs/efs-utils.conf`):

```# Validate the certificate hostname�| on mount. This option is not supported by certain stunnel versions.```

Deleting this character resolves the issue.

**Comment by Cappuccinuo** [comment]
Hey @mark-sinclair ,

Based on the config file in the repo, https://github.com/aws/efs-utils/blob/master/dist/efs-utils.conf#L26, there is no special character, can you check `git status` in your checked repo to see if there is anything change in the config file before the installation? Or the change is after you run `./build-deb.sh`.

Also what's the ami id you use? I just tried to install and mount on `ami-085925f297f89fce1`, and it works fine. Is this happen everytime you install the package? Can you remove the package, delete this config file under /etc/amazon/efs and try again?

Thanks.

**Comment by mark-sinclair** [comment]
Hi thanks for the reply. 

I am using ami-0701e7be9b2a77600 -- Ubuntu Server 18.04 LTS (HVM), SSD Volume Type -- with an m5.large instance in the eu-west-1 region.

Note that the character can be observed even before installing the utils.  If I launch a fresh instance and simply type the following 2 lines (nothing else)...

```
git clone https://github.com/aws/efs-utils
vi efs-utils/dist/efs-utils.conf
```
...then the character is visible. Note, that the character does not show on github, only after cloning the repo and checking it with `vi` (it also doesn't show with other bash commands like `more` ). 

I have also observed the same character if I clone the repo on my local (non-EC2) ubuntu machine. 

Also, here is the actual binary of the file for that region (using `hexdump -C`):

```
00000330  2f 65 66 73 2d 75 74 69  6c 73 2e 63 72 74 0a 0a  |/efs-utils.crt..|
00000340  23 20 56 61 6c 69 64 61  74 65 20 74 68 65 20 63  |# Validate the c|
00000350  65 72 74 69 66 69 63 61  74 65 20 68 6f 73 74 6e  |ertificate hostn|
00000360  61 6d 65 c2 a0 6f 6e 20  6d 6f 75 6e 74 2e 20 54  |ame..on mount. T|
00000370  68 69 73 20 6f 70 74 69  6f 6e 20 69 73 20 6e 6f  |his option is no|
```

You can see that there is an extra `a0` byte which is beyond the range of conventional ASCII. Maybe someone was typing in utf8 and accidentally hit a modifier key (such as those used to add accents to lettters)?

**Comment by Cappuccinuo** [comment]
Thanks for the detail report, we will have someone fix this.

**Comment by mark-sinclair** [comment]
@Cappuccinuo -- great, thanks! 

I also tried it with the ami you mentioned ( `ami-085925f297f89fce1` ) and I still have the same error message when trying to mount. 

Again, I have a fresh instance and run only these commands:

```
sudo apt -y update
sudo apt -y upgrade #tried with and without this line, same issue
sudo apt -y install binutils

git clone https://github.com/aws/efs-utils
cd efs-utils || exit
./build-deb.sh
sudo apt -y install ./build/amazon-efs-utils*deb
cd .. || exit

mkdir test
sudo mount -t efs fs-12345678:/ test

Traceback (most recent call last):
  File "/sbin/mount.efs", line 1577, in <module>
    main()
  File "/sbin/mount.efs", line 1556, in main
    config = read_config()
  File "/sbin/mount.efs", line 1217, in read_config
    p.read(config_file)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 867: ordinal not in range(128)
```

**Comment by Cappuccinuo** [comment]
I tried launching a new instance and install with your steps, but can mount successfully.

However If I manual type the line and delete original line, it has git diff.

Before
```bash
00000340  23 20 56 61 6c 69 64 61  74 65 20 74 68 65 20 63  |# Validate the c|
00000350  65 72 74 69 66 69 63 61  74 65 20 68 6f 73 74 6e  |ertificate hostn|
00000360  61 6d 65 c2 a0 6f 6e 20  6d 6f 75 6e 74 2e 20 54  |ame..on mount. T|
```
After
```bash
00000340  23 20 56 61 6c 69 64 61  74 65 20 74 68 65 20 63  |# Validate the c|
00000350  65 72 74 69 66 69 63 61  74 65 20 68 6f 73 74 6e  |ertificate hostn|
00000360  61 6d 65 20 6f 6e 20 6d  6f 75 6e 74 2e 20 54 68  |ame on mount. Th|
```

**Comment by mark-sinclair** [comment]
@Cappuccinuo I tested the again with the new merged change that removes the characters. Everyone is working fine for me now -- many thanks for fixing it so quickly!
