### ISSUE TITLE
Put the "RELEASE" number back in as a separate attribute

### ISSUE THREAD

**Issue by nkadel** [aws/efs-utils#67]
The new "VERSION" number of "1.25-3" violates semvar and is inconsistent with tarballs being based on the "Version" setting for .spec files. Please revert that change and go back to "$VERSION-$RELEASE" numbering schemes.

If you want to follow a more detailed numbering scheme, then use "1.25.3" to show minor, compatible sub releases according to the "semver" numbering standards laid out at https://semver.org/ . This is the standard followed by Gnu projects, Apache projects, python, and rubygems for example

**Comment by Cappuccinuo** [comment]
@nkadel , thanks for the feedback.

It is reasonable to change version to `MAJOR.MINOR.PATCH` based on the semver standard. We will have someone fix this.

**Comment by nkadel** [comment]
Thank you! How responsive!

**Comment by Cappuccinuo** [comment]
Hey @nkadel , we changed the version to `MAJOR.MINOR.PATCH` in most recent release.
