### ISSUE TITLE
watchdog sometimes fails to restart stunnel for some mounts causing read/write to hang

### ISSUE THREAD

**Issue by wongma7** [aws/efs-utils#69]
**What happened**

Say I have >=2 tls-enabled mounts.

127.0.0.1:/ on /var/lib/kubelet/asdf type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,port=20313,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)

127.0.0.1:/ on /var/lib/kubelet/qwer type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,port=20236,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)

If I stop all stunnel processes, sometimes watchdog fails to restart all of them.

In this case it successfully restarts `stunnel  /var/run/efs/stunnel-config.fs-fb878251.var.lib.kubelet.qwer.20236` but then skips the other one, incorrectly determining it to already be running:
2020-06-05 07:58:07,391 - DEBUG - TLS tunnel for fs-fb878251.var.lib.kubelet.asdf.20133 is running

Since stunnel is not running, all read/writes to /var/lib/kubelet/asdf hang and in dmesg I see this:
[2521412.689613] nfs: server 127.0.0.1 not responding, timed out

The state files show that both stunnel processes are somehow supposed to have PID 19 which is impossible:

bash-4.2# cat /var/run/efs/fs-fb878251.var.lib.kubelet.qwer.20236
{"files": ["/var/run/efs/stunnel-config.fs-fb878251.var.lib.kubelet.qwer.20236"], "cmd": ["stunnel", "/var/run/efs/stunnel-config.fs-fb878251.var.lib.kubelet.qwer.20236"], "pid": 19}

bash-4.2# cat /var/run/efs/fs-fb878251.var.bash-4.2# cat /var/run/efs/fs-fb878251.var.lib.kubelet.asdf.20313
{"files": ["/var/run/efs/stunnel-config.fs-fb878251.var.lib.kubelet.asdf.20313"], "cmd": ["stunnel", "/var/run/efs/stunnel-config.fs-fb878251.var.lib.kubelet.asdf.20313"], "pid": 19}

**Possible explanation**

It can arrive at this broken state like this:
1. Read /var/run/efs/fs-fb878251.var.lib.kubelet.qwer.20236. It had pid=123 before being killed.
2. Restart `stunnel /var/run/efs/fs-fb878251.var.lib.kubelet.qwer.20236`. It has new pid=19
3. Write /var/run/efs/fs-fb878251.var.lib.kubelet.qwer.20236 pid=19
4. Read /var/run/efs/stunnel-config.fs-fb878251.var.lib.kubelet.asdf.20313. It had pid=19 before being killed.
5. Internal state says there is already an stunnel process running at pid=19 (the one started at step 2). https://github.com/aws/efs-utils/blob/master/src/watchdog/__init__.py#L457
6. No-op instead of restarting `stunnel /var/run/efs/fs-fb878251.var.lib.kubelet.asdf.20313`
7. Read writes to /var/lib/kubelet/asdf fail.

**More context**

I ran into this issue when testing https://github.com/kubernetes-sigs/aws-efs-csi-driver. It's easy to simulate "stop all stunnel processes" by restarting the container becaue then all the mounts and state files persist but not the watchdog and stunnel processes. Since there are no other processes in the container besides aws-efs-csi-driver, watchdog, and stunnel, it's quite likely that new stunnel processes started by watchdog get pids that conflict with the pids of old stunnel processes (like pid 19 in my example) and trigger this issue.

**Comment by lilferna** [comment]
Thanks for the feedback. We’ll have someone take a look and post a more detailed response once we better understand the issue.

**Comment by kbasv** [comment]
A fix was pushed out in the latest release for efs-utils v1.26.2. Closing this issue.
