### ISSUE TITLE
New "already mounted"-check is a breaking change for systemd automount users

### ISSUE THREAD

**Issue by pitkley** [aws/efs-utils#73]
We are using EFS-mounts in combination with [systemd.automount-units](https://www.freedesktop.org/software/systemd/man/systemd.automount.html). systemd.automount creates a virtual mountpoint which, upon access, will be shadowed by the actual mountpoint. This gives two benefits:

* Volumes are only actually mounted when required.
* If the volume was unmounted, either due to an error or on purpose, a subsequent access will mount it again.

Unfortunately the recent commit 7fec61b breaks this feature by [checking if the volume is already mounted](https://github.com/aws/efs-utils/commit/7fec61bd4a8680c3a5dfd32519d9baaa9faa2b04#diff-b53ac8f3da58b57df5e7bd528c677e20R1493-R1496). In the case of systemd.automount there will be the virtual mount I talked about, which looks like this:

```console
$ mount /efs
systemd-1 on /efs type autofs (...)
```

After the directory has been accessed (with 1.25-2 or below) the new mount simply shadows the automount:

```console
$ ls /efs
...
$ mount /efs
systemd-1 on /efs type autofs (...)
127.0.0.1:/ on /efs type nfs4 (...)
```

1.25-3 is a breaking change for this use-case, since mounting a TLS-enabled EFS-mount is now no longer possible.

----

Example units. `/etc/systemd/system/efs.mount`:

```
[Unit]
After=network.target network-online.target
Wants=network-online.target

[Mount]
What=fs-INSERTID:/
Where=/efs
Type=efs
Options=tls
```

`/etc/systemd/system/efs.automount`:

```
[Automount]
Where=/efs

[Install]
WantedBy=multi-user.target
```

The automount is enabled through `systemctl enable --now efs.automount`.

**Comment by pitkley** [comment]
My initial suggestion on how to fix this would be to extend the `.ismount`-check to identify what filesystem-type is mounted, and only exit early if `nfs4` is used.

Since I'm not sure how much development resources are available to quickly fix and test this, I'd appreciate if a 1.25-4 could be published which reverts commit 7fec61b. (We have patched out the code in our images manually for the time being.)

I'm happy to help with testing if required!

**Comment by Cappuccinuo** [comment]
Hey @pitkley ,

Thanks for your feedback. Your suggestion is reasonable, please use <v1.25-3 or use your patch if using `systemd.automount-units`. We will have someone fix this.

**Comment by pitkley** [comment]
Thanks for the quick response, @Cappuccinuo, much appreciated! :+1:

**Comment by Cappuccinuo** [comment]
@pitkley ,

Could you please pull the mainline code, (make the rpm)/(build the deb) and re-test, we push the fix just now.

Thanks.

**Comment by pitkley** [comment]
Hi @Cappuccinuo, thanks for the notification.

I built and installed the RPM from master and can confirm that it is working as desired:

* The volume is not mounted.
* Accessing the mountpoint triggers the systemd automount.
* systemd will execute `mount.efs`.
* `mount.efs` will `stat` the mountpoint. While a `stat` is enough to trigger the mount, systemd is smart enough not to cause a loop, allowing `stat` to correctly return `autofs` (which is the systemd-automount).
* `mount.efs` will correctly mount the EFS-volume.
* The access succeeds.

I'm happy to close the issue, although it would be nice if you could quickly notify me when the package is available in the Amazon Linux (2) repos.

**Comment by Cappuccinuo** [comment]
Hey @pitkley ,

I will leave this issue open and notify you when the package is available in AL repo.

Thanks.

**Comment by Cappuccinuo** [comment]
Hey @pitkley ,

v1.26.2 is available in AL repo.

Thanks.

**Comment by pitkley** [comment]
@Cappuccinuo thanks for informing me. I can confirm that the latest version fixes the issue I had. Thanks for the quick turnaround on this fix to everyone involved! :+1:
