### ISSUE TITLE
Terminating stunnel process in nondeterministic; might get stuck or kill other processes

### ISSUE THREAD

**Issue by devkid** [aws/efs-utils#75]
The PID of the stunnel process is stored in the state file. The watchdog will regularly check if a mount is expired and - if it is and a process with this PID is still running - tries do kill it. However, this is nondeterministic as other processes or threads might have taken the PID was killed or has died in between.

We just had at least one case where the `efs-plugin` container of the `efs-csi-node` daemonset on EKS was killed because it ran out of memory. In the mean time, application pods using the EFS mounts were recreated to try to get them unstuck. As the state files of the watchdog etc. are persisted across container (and even pod) restarts, the new watchdog process noticed that it's state file contains an expired mount. It tried to clean it up by terminating the stunnel process with PID 21 (which was persisted in the state file). However, PID 21 was now the thread ID of a go thread of the `aws-efs-csi-driver` process. So [it gets the process group ID of this thread (which is PGID 1 = aws-efs-csi-driver) and sends a SIGTERM to it](https://github.com/aws/efs-utils/blob/master/src/watchdog/__init__.py#L382), resulting in all processes in the container to receive a SIGTERM (we verified this by running `sleep 3` in the container, which got killed after a second). If not running in a container, this could be much more dangerous (i.e. sending signals to the init process of the system). This process repeated again and again because the PID it tried to kill (21) belonged to PID 1 in the container which just ignored the SIGTERM, so it got stuck.

I guess to solve this you would need to use some real process manager like supervisord or systemd (that uses cgroups) to start and manage the stunnel processes.

**Comment by devkid** [comment]
Might be related to #74.

**Comment by kbasv** [comment]
Hi @devkid 

Thanks for reporting the issue. Can you provide the version of efs-utils that is being used inside efs-csi-node daemonset?

**Comment by devkid** [comment]
We are using version 1.25-1.amzn2 but with the [this PR](https://github.com/aws/efs-utils/pull/60) (to get support and for IRSA) and [this branch](https://github.com/LogMeIn/efs-utils/compare/feature/credentials-via-web-identity...LogMeIn:feature/move-private-key-location) (to fix https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/178) applied, both of which shouldn't have any influence on the described problem.

**Comment by devkid** [comment]
I guess this might be fixed with https://github.com/aws/efs-utils/commit/87a868ec925279b251c530fd518010213d550c08 already.
