### ISSUE TITLE
Mounting with IAM authorization does not work with IMDSv2

### ISSUE THREAD

**Issue by damianwinkowski** [aws/efs-utils#80]
Hi,
after enabling IMDSv2 it appears that mounting with `iam` option does not work (using security credentials from instance metadata) . After reviewing the source code it seems like `get_aws_ec2_metadata_token` is only used for retrieving region from instance metadata.

1. Setup: EC2 with InstanceProfile
2. How do I mount efs:
`mount -t efs -o tls,iam fs-xxxxxxx:/ /mnt/MountPointHere`
3. Response I get:
`AWS Access Key ID and Secret Access Key are not found in AWS credentials file (/root/.aws/credentials), config file (/root/.aws/config), from ECS credentials relative uri, or from the instance security credentials service`

**Comment by Cappuccinuo** [comment]
Hey @damianwinkowski ,

Thanks for your feedback. I can reproduce on my side, you are right that the url curl is unauthorized since metadata_token is only used when retrieving region from instance metadata. We will have someone take a look at this issue.

**Comment by Cappuccinuo** [comment]
Hey @damianwinkowski ,

Could you please try the new commit in the Github which should fix this issue? (version v1.28.2-1) Thanks.

**Comment by damianwinkowski** [comment]
Hi @Cappuccinuo ,
it works like a charm. Appreciate your effort and quick turnaround.

Thanks.
