### ISSUE TITLE
Error message is a red herring, consider changing the phrase

### ISSUE THREAD

**Issue by nathanpeck** [aws/efs-utils#90]
This line of code and the resulting error message can be triggered when there is no mount target added to the VPC: https://github.com/aws/efs-utils/blob/master/src/mount_efs/__init__.py#L1534

In specific if a user attempts to mount an EFS volume when there is no mount target in their VPC they will trigger this error and will end up seeing an error message that says: `Failed to resolve "fs-xxxxxxxxxx.efs.us-west-1.amazonaws.com" - check that your file system ID is correct.`

This is a red herring error message because the file system ID may be correct, yet did not resolve for another reason. I would suggest modifying the error message to say something like "Please ensure that the VPC has an EFS mount target for this filesystem ID"

**Comment by Cappuccinuo** [comment]
Hey @nathanpeck , thanks for the feedback, we'll have someone to take a look
