### ISSUE TITLE
Changing tags causes fetch to fail

### ISSUE THREAD

**Issue by Benabik** [aws/efs-utils#92]
Twice now it seems that this repository has changed the value of a tag.  I don't have details on the first, but currently a `git fetch origin --tags` on my clone gives me this error:

```
$ git fetch origin --tags
From https://github.com/aws/efs-utils
 ! [rejected]        v1.30.2    -> v1.30.2  (would clobber existing tag)
```

Using rev-parse, I can see that my copy of v1.30.2 points to a07e4181e69b62a0f38d847f80d42a74bb70ac8d, but looking at the web site, I can see that v1.30.2 is now c5abeed1a90a20c0ac0ad1a592296f795cd33e7c.

I can update my script to force-overwrite tags to solve my immediate issue but I thought I would raise that this is a problem, especially for automated sync or deployment.

**Comment by Cappuccinuo** [comment]
Hey @Benabik , thanks for the feedback and apologize for the trouble. 

We merged in a small fix in the Github so redirect the tag commit. Will avoid this next time and bump the version instead of modify tags.

**Comment by Cappuccinuo** [comment]
Close this issue for now. We will avoid modify the tag directly in the future. Thanks.
