### ISSUE TITLE
Suggestion: allow specifying fs_id in cloudwatch log group name

### ISSUE THREAD

**Issue by derbeneviv** [aws/efs-utils#93]
Currently only plaintext log groups are supported, like:
```
[cloudwatch-log]
# enabled = true
log_group_name = /aws/efs/utils
```

**Suggestion:**  
Allow specifying a templated {fs_id} to then make a cloudwatch metrics based on it
```
[cloudwatch-log]
# enabled = true
log_group_name = /aws/efs/utils/{fs_id}
```

**UseCase**:  
We want to make a MountFailure metric & alarm. But the only place from where we consistently can get a fs_id for every error message is a cloudwatch logstream name, and Cloudwatch MetcricFilter can't use a logstream name as a dimension    
Specifying per-efsid logGroup can allow making a separate metricFilter for each efs id

**Comment by bahildebrand** [comment]
@derbeneviv thanks for the feedback. We'll have someone take a look and get back to you.
