### ISSUE TITLE
stunnel 4.56 memory leak

### ISSUE THREAD

**Issue by justinc1** [aws/efs-utils#99]
We have t3.small instances, they are used as ECS hosts. Recently some of deployed (re-deployed, e.g. they were upgraded) containers didn't work, and in ECS dashboard under Clusters > Cluster-name > ECS Instances the "Agent connected" was false. In EC2 we could not open shell session to such instance.

Some containers also started to occasionally report memory allocation problems, so we were guessing this is memory related. We were able to reproduce this once, and additional hint was that EC2 instance CPU usage was at 50% (e.g. 1 of 2 cores).

After more debugging, we see that EFS is using stunnel, and on some of our ECS instances stunnel processes has high RRS memory usage - about 200 MB. We have 5 EFS mounts on each ECS instance, so this consumed 1 GB of memory (1 half of total 2 GB). Each stunnel process leaks about 1.8 MB per day - ECS age was about 110 days.

For test I run ECS instance, with 5 EFS mounts, and no container. I wanted to check if leak happens only when EFS is being actively used. The stunnel does leak memory:

```
top output, collected every hour

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 3545 root      20   0  114472   5884   4992 S   0.0  0.3   0:00.01 stunnel
 3545 root      20   0  114604   5936   4992 S   0.0  0.3   0:00.03 stunnel
 3545 root      20   0  114604   5936   4992 S   0.0  0.3   0:00.04 stunnel
 3545 root      20   0  114736   6196   4992 S   0.0  0.3   0:00.05 stunnel
 3545 root      20   0  114736   6196   4992 S   0.0  0.3   0:00.05 stunnel
 3545 root      20   0  114868   6196   4992 S   0.0  0.3   0:00.06 stunnel
 3545 root      20   0  114868   6196   4992 S   0.0  0.3   0:00.06 stunnel
 3545 root      20   0  115000   6460   4992 S   0.0  0.3   0:00.07 stunnel
 3545 root      20   0  115000   6460   4992 S   0.0  0.3   0:00.09 stunnel
 3545 root      20   0  115128   6600   4992 S   0.0  0.3   0:00.09 stunnel
 3545 root      20   0  115128   6600   4992 S   0.0  0.3   0:00.10 stunnel
 3545 root      20   0  115128   6720   4992 S   0.0  0.3   0:00.10 stunnel
 3545 root      20   0  115260   6732   4992 S   0.0  0.3   0:00.11 stunnel
 3545 root      20   0  115260   6732   4992 S   0.0  0.3   0:00.11 stunnel
 3545 root      20   0  115388   6860   4992 S   0.0  0.3   0:00.13 stunnel
 3545 root      20   0  115388   6860   4992 S   0.0  0.3   0:00.13 stunnel
 3545 root      20   0  115520   6860   4992 S   0.0  0.3   0:00.14 stunnel
 3545 root      20   0  115520   6860   4992 S   0.0  0.3   0:00.14 stunnel
 3545 root      20   0  115652   7120   4992 S   0.0  0.4   0:00.16 stunnel
```

I'm currently testing stunnel-5.59, compiled per instructions on https://docs.aws.amazon.com/efs/latest/ug/upgrading-stunnel.html. Seems to work, after initial 500 KB jump in RSS it was than stable for last 10+ hours.

But to install this stunnel binary I will have to manually replace /usr/bin/stunnel. Is there a way to get more recent stunnel available in official yum repos? Or some other alternative?

Our EC2 image is based on Amazon linux
```
[root@ip-10-200-233-61 bin]# rpm -qa | grep -e efs -e stunnel
amazon-efs-utils-1.30.1-1.amzn2.noarch
stunnel-4.56-6.amzn2.0.3.x86_64
```

**Comment by Cappuccinuo** [comment]
Thanks for the feedback. We will have someone to take a look.

**Comment by KatharinaSt** [comment]
I am also experiencing issues with increasing memory over time on AWS EC2 instances.

The memory instantly drops on restarting stunnel4 service.

stunnel Version: 5.44 (latest version for Ubuntu 18.04 LTS (bionic))
https://packages.ubuntu.com/bionic/stunnel4

**Comment by adrianalexe** [comment]
I've just encountered the same issue. The _stunnel_ process had been running since 2020, and needed a restart, as it was already up to 38% RAM usage.

Before:
```
root      2638  0.0 38.1 864472 765696 ?       Ssl   2020   2:55 /usr/bin/stunnel
```

After:
```
root      6094  0.0  0.2  44676  5232 ?        Ss   17:27   0:00 /usr/bin/stunnel
```
More information:
```
# cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
```
# rpm -qa | grep -e efs -e stunnel
stunnel-4.56-6.amzn2.0.3.x86_64
amazon-efs-utils-1.27.1-1.amzn2.noarch
```

**Comment by Cappuccinuo** [comment]
The `stunnel` shipped with AL2022 is stunnel5+ so if you don't want to upgrade the stunnel manually on each new instance, you can consider to move to use AL2022. 

For AL2 + Stunnel4.56 which has the memory leak issue, we are coordinating to find path to update the yum repo, please follow https://docs.aws.amazon.com/efs/latest/ug/upgrading-stunnel.html for now, and upgrade the stunnel to latest version.

**Comment by msolberg8** [comment]
@Cappuccinuo is there any eta on the path to update the yum repo?

**Comment by Cappuccinuo** [comment]
We are still waiting on AL2 yum repository side to ship the stunnel 5.x which is expected to be done within this month. 

Once the software is there, we can change the spec file on efs-utils side.

**Comment by msolberg8** [comment]
@Cappuccinuo any progress here?

**Comment by Cappuccinuo** [comment]
Amazon Linux will release the stunnel5 to AL2 yum repository within this week, will keep you guys updated once that package is merged.

**Comment by bryanasdev000** [comment]
> Amazon Linux will release the stunnel5 to AL2 yum repository within this week, will keep you guys updated once that package is merged.

Hi @Cappuccinuo, sorry to bump again, but there is a place we can check?

I just give a quick spin to a EC2 using AL2 and stunnel version still 4.56 (`4.56-6.amzn2.0.3`)

Just for reference, my pain point is https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/474 and so, once this is up and running we probably need to wait a release there too.

Thanks in advance.

**Comment by Cappuccinuo** [comment]
The stunnel5 package has been released but the global availability date is 8/19, so the package won't be globally available at that time. 

And efs-utils will need to be changed to use that stunnel5 namespace for AL2 after that, we are working on that change and planning on that release.

**Comment by msolberg8** [comment]
@Cappuccinuo any idea when that release is planned for?

**Comment by snoord** [comment]
Looks like [efs-utils v1.34.2](https://github.com/aws/efs-utils/releases/tag/v1.34.2) has the necessary stunnel5 + AL2 namespace changes to potentially resolve this issue

**Comment by Cappuccinuo** [comment]
Yes, from efs-utils v1.34.1 we use stunnel5.58 for Amazon Linux 2, and that version stunnel will not have the memory leak issue. v1.34.2 fix some potential issue in csi-driver.

**Comment by justinc1** [comment]
This issue has been closed years ago @ralessandro-mox :)

stunnel restart - your stunnel is likely being used by EFS. I would not try to restart only stunnel while EFS is in use. Restart whole EC2 instance instead. Or better, experiment with more up-to-date stunnel version.
